// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/proto/examplepb/a_bit_of_everything.proto

package examplepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import pathenum "github.com/grpc-ecosystem/grpc-gateway/examples/proto/pathenum"
import sub "github.com/grpc-ecosystem/grpc-gateway/examples/proto/sub"
import sub2 "github.com/grpc-ecosystem/grpc-gateway/examples/proto/sub2"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import field_mask "google.golang.org/genproto/protobuf/field_mask"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// NumericEnum is one or zero.
type NumericEnum int32

const (
	// ZERO means 0
	NumericEnum_ZERO NumericEnum = 0
	// ONE means 1
	NumericEnum_ONE NumericEnum = 1
)

var NumericEnum_name = map[int32]string{
	0: "ZERO",
	1: "ONE",
}
var NumericEnum_value = map[string]int32{
	"ZERO": 0,
	"ONE":  1,
}

func (x NumericEnum) String() string {
	return proto.EnumName(NumericEnum_name, int32(x))
}
func (NumericEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_0880245b62d9020b, []int{0}
}

// DeepEnum is one or zero.
type ABitOfEverything_Nested_DeepEnum int32

const (
	// FALSE is false.
	ABitOfEverything_Nested_FALSE ABitOfEverything_Nested_DeepEnum = 0
	// TRUE is true.
	ABitOfEverything_Nested_TRUE ABitOfEverything_Nested_DeepEnum = 1
)

var ABitOfEverything_Nested_DeepEnum_name = map[int32]string{
	0: "FALSE",
	1: "TRUE",
}
var ABitOfEverything_Nested_DeepEnum_value = map[string]int32{
	"FALSE": 0,
	"TRUE":  1,
}

func (x ABitOfEverything_Nested_DeepEnum) String() string {
	return proto.EnumName(ABitOfEverything_Nested_DeepEnum_name, int32(x))
}
func (ABitOfEverything_Nested_DeepEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_0880245b62d9020b, []int{0, 0, 0}
}

// Intentionaly complicated message type to cover many features of Protobuf.
// NEXT ID: 30
type ABitOfEverything struct {
	SingleNested        *ABitOfEverything_Nested                `protobuf:"bytes,25,opt,name=single_nested,json=singleNested,proto3" json:"single_nested,omitempty"`
	Uuid                string                                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Nested              []*ABitOfEverything_Nested              `protobuf:"bytes,2,rep,name=nested,proto3" json:"nested,omitempty"`
	FloatValue          float32                                 `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	DoubleValue         float64                                 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	Int64Value          int64                                   `protobuf:"varint,5,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Uint64Value         uint64                                  `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Int32Value          int32                                   `protobuf:"varint,7,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Fixed64Value        uint64                                  `protobuf:"fixed64,8,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	Fixed32Value        uint32                                  `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"`
	BoolValue           bool                                    `protobuf:"varint,10,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	StringValue         string                                  `protobuf:"bytes,11,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BytesValue          []byte                                  `protobuf:"bytes,29,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	Uint32Value         uint32                                  `protobuf:"varint,13,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	EnumValue           NumericEnum                             `protobuf:"varint,14,opt,name=enum_value,json=enumValue,proto3,enum=grpc.gateway.examples.examplepb.NumericEnum" json:"enum_value,omitempty"`
	PathEnumValue       pathenum.PathEnum                       `protobuf:"varint,30,opt,name=path_enum_value,json=pathEnumValue,proto3,enum=grpc.gateway.examples.pathenum.PathEnum" json:"path_enum_value,omitempty"`
	NestedPathEnumValue pathenum.MessagePathEnum_NestedPathEnum `protobuf:"varint,31,opt,name=nested_path_enum_value,json=nestedPathEnumValue,proto3,enum=grpc.gateway.examples.pathenum.MessagePathEnum_NestedPathEnum" json:"nested_path_enum_value,omitempty"`
	Sfixed32Value       int32                                   `protobuf:"fixed32,15,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"`
	Sfixed64Value       int64                                   `protobuf:"fixed64,16,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	Sint32Value         int32                                   `protobuf:"zigzag32,17,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"`
	Sint64Value         int64                                   `protobuf:"zigzag64,18,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	RepeatedStringValue []string                                `protobuf:"bytes,19,rep,name=repeated_string_value,json=repeatedStringValue,proto3" json:"repeated_string_value,omitempty"`
	// Types that are valid to be assigned to OneofValue:
	//	*ABitOfEverything_OneofEmpty
	//	*ABitOfEverything_OneofString
	OneofValue               isABitOfEverything_OneofValue       `protobuf_oneof:"oneof_value"`
	MapValue                 map[string]NumericEnum              `protobuf:"bytes,22,rep,name=map_value,json=mapValue,proto3" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=grpc.gateway.examples.examplepb.NumericEnum"`
	MappedStringValue        map[string]string                   `protobuf:"bytes,23,rep,name=mapped_string_value,json=mappedStringValue,proto3" json:"mapped_string_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MappedNestedValue        map[string]*ABitOfEverything_Nested `protobuf:"bytes,24,rep,name=mapped_nested_value,json=mappedNestedValue,proto3" json:"mapped_nested_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NonConventionalNameValue string                              `protobuf:"bytes,26,opt,name=nonConventionalNameValue,proto3" json:"nonConventionalNameValue,omitempty"`
	TimestampValue           *timestamp.Timestamp                `protobuf:"bytes,27,opt,name=timestamp_value,json=timestampValue,proto3" json:"timestamp_value,omitempty"`
	// repeated enum value. it is comma-separated in query
	RepeatedEnumValue []NumericEnum `protobuf:"varint,28,rep,packed,name=repeated_enum_value,json=repeatedEnumValue,proto3,enum=grpc.gateway.examples.examplepb.NumericEnum" json:"repeated_enum_value,omitempty"`
	// repeated numeric enum comment (This comment is overridden by the field annotation)
	RepeatedEnumAnnotation []NumericEnum `protobuf:"varint,32,rep,packed,name=repeated_enum_annotation,json=repeatedEnumAnnotation,proto3,enum=grpc.gateway.examples.examplepb.NumericEnum" json:"repeated_enum_annotation,omitempty"`
	// numeric enum comment (This comment is overridden by the field annotation)
	EnumValueAnnotation NumericEnum `protobuf:"varint,33,opt,name=enum_value_annotation,json=enumValueAnnotation,proto3,enum=grpc.gateway.examples.examplepb.NumericEnum" json:"enum_value_annotation,omitempty"`
	// repeated string comment (This comment is overridden by the field annotation)
	RepeatedStringAnnotation []string `protobuf:"bytes,34,rep,name=repeated_string_annotation,json=repeatedStringAnnotation,proto3" json:"repeated_string_annotation,omitempty"`
	// repeated nested object comment (This comment is overridden by the field annotation)
	RepeatedNestedAnnotation []*ABitOfEverything_Nested `protobuf:"bytes,35,rep,name=repeated_nested_annotation,json=repeatedNestedAnnotation,proto3" json:"repeated_nested_annotation,omitempty"`
	// nested object comments (This comment is overridden by the field annotation)
	NestedAnnotation     *ABitOfEverything_Nested `protobuf:"bytes,36,opt,name=nested_annotation,json=nestedAnnotation,proto3" json:"nested_annotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ABitOfEverything) Reset()         { *m = ABitOfEverything{} }
func (m *ABitOfEverything) String() string { return proto.CompactTextString(m) }
func (*ABitOfEverything) ProtoMessage()    {}
func (*ABitOfEverything) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_0880245b62d9020b, []int{0}
}
func (m *ABitOfEverything) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ABitOfEverything.Unmarshal(m, b)
}
func (m *ABitOfEverything) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ABitOfEverything.Marshal(b, m, deterministic)
}
func (dst *ABitOfEverything) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ABitOfEverything.Merge(dst, src)
}
func (m *ABitOfEverything) XXX_Size() int {
	return xxx_messageInfo_ABitOfEverything.Size(m)
}
func (m *ABitOfEverything) XXX_DiscardUnknown() {
	xxx_messageInfo_ABitOfEverything.DiscardUnknown(m)
}

var xxx_messageInfo_ABitOfEverything proto.InternalMessageInfo

func (m *ABitOfEverything) GetSingleNested() *ABitOfEverything_Nested {
	if m != nil {
		return m.SingleNested
	}
	return nil
}

func (m *ABitOfEverything) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ABitOfEverything) GetNested() []*ABitOfEverything_Nested {
	if m != nil {
		return m.Nested
	}
	return nil
}

func (m *ABitOfEverything) GetFloatValue() float32 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *ABitOfEverything) GetDoubleValue() float64 {
	if m != nil {
		return m.DoubleValue
	}
	return 0
}

func (m *ABitOfEverything) GetInt64Value() int64 {
	if m != nil {
		return m.Int64Value
	}
	return 0
}

func (m *ABitOfEverything) GetUint64Value() uint64 {
	if m != nil {
		return m.Uint64Value
	}
	return 0
}

func (m *ABitOfEverything) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *ABitOfEverything) GetFixed64Value() uint64 {
	if m != nil {
		return m.Fixed64Value
	}
	return 0
}

func (m *ABitOfEverything) GetFixed32Value() uint32 {
	if m != nil {
		return m.Fixed32Value
	}
	return 0
}

func (m *ABitOfEverything) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *ABitOfEverything) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *ABitOfEverything) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *ABitOfEverything) GetUint32Value() uint32 {
	if m != nil {
		return m.Uint32Value
	}
	return 0
}

func (m *ABitOfEverything) GetEnumValue() NumericEnum {
	if m != nil {
		return m.EnumValue
	}
	return NumericEnum_ZERO
}

func (m *ABitOfEverything) GetPathEnumValue() pathenum.PathEnum {
	if m != nil {
		return m.PathEnumValue
	}
	return pathenum.PathEnum_ABC
}

func (m *ABitOfEverything) GetNestedPathEnumValue() pathenum.MessagePathEnum_NestedPathEnum {
	if m != nil {
		return m.NestedPathEnumValue
	}
	return pathenum.MessagePathEnum_GHI
}

func (m *ABitOfEverything) GetSfixed32Value() int32 {
	if m != nil {
		return m.Sfixed32Value
	}
	return 0
}

func (m *ABitOfEverything) GetSfixed64Value() int64 {
	if m != nil {
		return m.Sfixed64Value
	}
	return 0
}

func (m *ABitOfEverything) GetSint32Value() int32 {
	if m != nil {
		return m.Sint32Value
	}
	return 0
}

func (m *ABitOfEverything) GetSint64Value() int64 {
	if m != nil {
		return m.Sint64Value
	}
	return 0
}

func (m *ABitOfEverything) GetRepeatedStringValue() []string {
	if m != nil {
		return m.RepeatedStringValue
	}
	return nil
}

type isABitOfEverything_OneofValue interface {
	isABitOfEverything_OneofValue()
}

type ABitOfEverything_OneofEmpty struct {
	OneofEmpty *empty.Empty `protobuf:"bytes,20,opt,name=oneof_empty,json=oneofEmpty,proto3,oneof"`
}

type ABitOfEverything_OneofString struct {
	OneofString string `protobuf:"bytes,21,opt,name=oneof_string,json=oneofString,proto3,oneof"`
}

func (*ABitOfEverything_OneofEmpty) isABitOfEverything_OneofValue() {}

func (*ABitOfEverything_OneofString) isABitOfEverything_OneofValue() {}

func (m *ABitOfEverything) GetOneofValue() isABitOfEverything_OneofValue {
	if m != nil {
		return m.OneofValue
	}
	return nil
}

func (m *ABitOfEverything) GetOneofEmpty() *empty.Empty {
	if x, ok := m.GetOneofValue().(*ABitOfEverything_OneofEmpty); ok {
		return x.OneofEmpty
	}
	return nil
}

func (m *ABitOfEverything) GetOneofString() string {
	if x, ok := m.GetOneofValue().(*ABitOfEverything_OneofString); ok {
		return x.OneofString
	}
	return ""
}

func (m *ABitOfEverything) GetMapValue() map[string]NumericEnum {
	if m != nil {
		return m.MapValue
	}
	return nil
}

func (m *ABitOfEverything) GetMappedStringValue() map[string]string {
	if m != nil {
		return m.MappedStringValue
	}
	return nil
}

func (m *ABitOfEverything) GetMappedNestedValue() map[string]*ABitOfEverything_Nested {
	if m != nil {
		return m.MappedNestedValue
	}
	return nil
}

func (m *ABitOfEverything) GetNonConventionalNameValue() string {
	if m != nil {
		return m.NonConventionalNameValue
	}
	return ""
}

func (m *ABitOfEverything) GetTimestampValue() *timestamp.Timestamp {
	if m != nil {
		return m.TimestampValue
	}
	return nil
}

func (m *ABitOfEverything) GetRepeatedEnumValue() []NumericEnum {
	if m != nil {
		return m.RepeatedEnumValue
	}
	return nil
}

func (m *ABitOfEverything) GetRepeatedEnumAnnotation() []NumericEnum {
	if m != nil {
		return m.RepeatedEnumAnnotation
	}
	return nil
}

func (m *ABitOfEverything) GetEnumValueAnnotation() NumericEnum {
	if m != nil {
		return m.EnumValueAnnotation
	}
	return NumericEnum_ZERO
}

func (m *ABitOfEverything) GetRepeatedStringAnnotation() []string {
	if m != nil {
		return m.RepeatedStringAnnotation
	}
	return nil
}

func (m *ABitOfEverything) GetRepeatedNestedAnnotation() []*ABitOfEverything_Nested {
	if m != nil {
		return m.RepeatedNestedAnnotation
	}
	return nil
}

func (m *ABitOfEverything) GetNestedAnnotation() *ABitOfEverything_Nested {
	if m != nil {
		return m.NestedAnnotation
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ABitOfEverything) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ABitOfEverything_OneofMarshaler, _ABitOfEverything_OneofUnmarshaler, _ABitOfEverything_OneofSizer, []interface{}{
		(*ABitOfEverything_OneofEmpty)(nil),
		(*ABitOfEverything_OneofString)(nil),
	}
}

func _ABitOfEverything_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ABitOfEverything)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *ABitOfEverything_OneofEmpty:
		b.EncodeVarint(20<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OneofEmpty); err != nil {
			return err
		}
	case *ABitOfEverything_OneofString:
		b.EncodeVarint(21<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.OneofString)
	case nil:
	default:
		return fmt.Errorf("ABitOfEverything.OneofValue has unexpected type %T", x)
	}
	return nil
}

func _ABitOfEverything_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ABitOfEverything)
	switch tag {
	case 20: // oneof_value.oneof_empty
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(empty.Empty)
		err := b.DecodeMessage(msg)
		m.OneofValue = &ABitOfEverything_OneofEmpty{msg}
		return true, err
	case 21: // oneof_value.oneof_string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofValue = &ABitOfEverything_OneofString{x}
		return true, err
	default:
		return false, nil
	}
}

func _ABitOfEverything_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ABitOfEverything)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *ABitOfEverything_OneofEmpty:
		s := proto.Size(x.OneofEmpty)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ABitOfEverything_OneofString:
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(len(x.OneofString)))
		n += len(x.OneofString)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Nested is nested type.
type ABitOfEverything_Nested struct {
	// name is nested field.
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount uint32 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// DeepEnum comment.
	Ok                   ABitOfEverything_Nested_DeepEnum `protobuf:"varint,3,opt,name=ok,proto3,enum=grpc.gateway.examples.examplepb.ABitOfEverything_Nested_DeepEnum" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ABitOfEverything_Nested) Reset()         { *m = ABitOfEverything_Nested{} }
func (m *ABitOfEverything_Nested) String() string { return proto.CompactTextString(m) }
func (*ABitOfEverything_Nested) ProtoMessage()    {}
func (*ABitOfEverything_Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_0880245b62d9020b, []int{0, 0}
}
func (m *ABitOfEverything_Nested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ABitOfEverything_Nested.Unmarshal(m, b)
}
func (m *ABitOfEverything_Nested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ABitOfEverything_Nested.Marshal(b, m, deterministic)
}
func (dst *ABitOfEverything_Nested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ABitOfEverything_Nested.Merge(dst, src)
}
func (m *ABitOfEverything_Nested) XXX_Size() int {
	return xxx_messageInfo_ABitOfEverything_Nested.Size(m)
}
func (m *ABitOfEverything_Nested) XXX_DiscardUnknown() {
	xxx_messageInfo_ABitOfEverything_Nested.DiscardUnknown(m)
}

var xxx_messageInfo_ABitOfEverything_Nested proto.InternalMessageInfo

func (m *ABitOfEverything_Nested) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ABitOfEverything_Nested) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ABitOfEverything_Nested) GetOk() ABitOfEverything_Nested_DeepEnum {
	if m != nil {
		return m.Ok
	}
	return ABitOfEverything_Nested_FALSE
}

// ABitOfEverythingRepeated is used to validate repeated path parameter functionality
type ABitOfEverythingRepeated struct {
	// repeated values. they are comma-separated in path
	PathRepeatedFloatValue    []float32     `protobuf:"fixed32,1,rep,packed,name=path_repeated_float_value,json=pathRepeatedFloatValue,proto3" json:"path_repeated_float_value,omitempty"`
	PathRepeatedDoubleValue   []float64     `protobuf:"fixed64,2,rep,packed,name=path_repeated_double_value,json=pathRepeatedDoubleValue,proto3" json:"path_repeated_double_value,omitempty"`
	PathRepeatedInt64Value    []int64       `protobuf:"varint,3,rep,packed,name=path_repeated_int64_value,json=pathRepeatedInt64Value,proto3" json:"path_repeated_int64_value,omitempty"`
	PathRepeatedUint64Value   []uint64      `protobuf:"varint,4,rep,packed,name=path_repeated_uint64_value,json=pathRepeatedUint64Value,proto3" json:"path_repeated_uint64_value,omitempty"`
	PathRepeatedInt32Value    []int32       `protobuf:"varint,5,rep,packed,name=path_repeated_int32_value,json=pathRepeatedInt32Value,proto3" json:"path_repeated_int32_value,omitempty"`
	PathRepeatedFixed64Value  []uint64      `protobuf:"fixed64,6,rep,packed,name=path_repeated_fixed64_value,json=pathRepeatedFixed64Value,proto3" json:"path_repeated_fixed64_value,omitempty"`
	PathRepeatedFixed32Value  []uint32      `protobuf:"fixed32,7,rep,packed,name=path_repeated_fixed32_value,json=pathRepeatedFixed32Value,proto3" json:"path_repeated_fixed32_value,omitempty"`
	PathRepeatedBoolValue     []bool        `protobuf:"varint,8,rep,packed,name=path_repeated_bool_value,json=pathRepeatedBoolValue,proto3" json:"path_repeated_bool_value,omitempty"`
	PathRepeatedStringValue   []string      `protobuf:"bytes,9,rep,name=path_repeated_string_value,json=pathRepeatedStringValue,proto3" json:"path_repeated_string_value,omitempty"`
	PathRepeatedBytesValue    [][]byte      `protobuf:"bytes,10,rep,name=path_repeated_bytes_value,json=pathRepeatedBytesValue,proto3" json:"path_repeated_bytes_value,omitempty"`
	PathRepeatedUint32Value   []uint32      `protobuf:"varint,11,rep,packed,name=path_repeated_uint32_value,json=pathRepeatedUint32Value,proto3" json:"path_repeated_uint32_value,omitempty"`
	PathRepeatedEnumValue     []NumericEnum `protobuf:"varint,12,rep,packed,name=path_repeated_enum_value,json=pathRepeatedEnumValue,proto3,enum=grpc.gateway.examples.examplepb.NumericEnum" json:"path_repeated_enum_value,omitempty"`
	PathRepeatedSfixed32Value []int32       `protobuf:"fixed32,13,rep,packed,name=path_repeated_sfixed32_value,json=pathRepeatedSfixed32Value,proto3" json:"path_repeated_sfixed32_value,omitempty"`
	PathRepeatedSfixed64Value []int64       `protobuf:"fixed64,14,rep,packed,name=path_repeated_sfixed64_value,json=pathRepeatedSfixed64Value,proto3" json:"path_repeated_sfixed64_value,omitempty"`
	PathRepeatedSint32Value   []int32       `protobuf:"zigzag32,15,rep,packed,name=path_repeated_sint32_value,json=pathRepeatedSint32Value,proto3" json:"path_repeated_sint32_value,omitempty"`
	PathRepeatedSint64Value   []int64       `protobuf:"zigzag64,16,rep,packed,name=path_repeated_sint64_value,json=pathRepeatedSint64Value,proto3" json:"path_repeated_sint64_value,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}      `json:"-"`
	XXX_unrecognized          []byte        `json:"-"`
	XXX_sizecache             int32         `json:"-"`
}

func (m *ABitOfEverythingRepeated) Reset()         { *m = ABitOfEverythingRepeated{} }
func (m *ABitOfEverythingRepeated) String() string { return proto.CompactTextString(m) }
func (*ABitOfEverythingRepeated) ProtoMessage()    {}
func (*ABitOfEverythingRepeated) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_0880245b62d9020b, []int{1}
}
func (m *ABitOfEverythingRepeated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ABitOfEverythingRepeated.Unmarshal(m, b)
}
func (m *ABitOfEverythingRepeated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ABitOfEverythingRepeated.Marshal(b, m, deterministic)
}
func (dst *ABitOfEverythingRepeated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ABitOfEverythingRepeated.Merge(dst, src)
}
func (m *ABitOfEverythingRepeated) XXX_Size() int {
	return xxx_messageInfo_ABitOfEverythingRepeated.Size(m)
}
func (m *ABitOfEverythingRepeated) XXX_DiscardUnknown() {
	xxx_messageInfo_ABitOfEverythingRepeated.DiscardUnknown(m)
}

var xxx_messageInfo_ABitOfEverythingRepeated proto.InternalMessageInfo

func (m *ABitOfEverythingRepeated) GetPathRepeatedFloatValue() []float32 {
	if m != nil {
		return m.PathRepeatedFloatValue
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedDoubleValue() []float64 {
	if m != nil {
		return m.PathRepeatedDoubleValue
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedInt64Value() []int64 {
	if m != nil {
		return m.PathRepeatedInt64Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedUint64Value() []uint64 {
	if m != nil {
		return m.PathRepeatedUint64Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedInt32Value() []int32 {
	if m != nil {
		return m.PathRepeatedInt32Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedFixed64Value() []uint64 {
	if m != nil {
		return m.PathRepeatedFixed64Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedFixed32Value() []uint32 {
	if m != nil {
		return m.PathRepeatedFixed32Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedBoolValue() []bool {
	if m != nil {
		return m.PathRepeatedBoolValue
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedStringValue() []string {
	if m != nil {
		return m.PathRepeatedStringValue
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedBytesValue() [][]byte {
	if m != nil {
		return m.PathRepeatedBytesValue
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedUint32Value() []uint32 {
	if m != nil {
		return m.PathRepeatedUint32Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedEnumValue() []NumericEnum {
	if m != nil {
		return m.PathRepeatedEnumValue
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedSfixed32Value() []int32 {
	if m != nil {
		return m.PathRepeatedSfixed32Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedSfixed64Value() []int64 {
	if m != nil {
		return m.PathRepeatedSfixed64Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedSint32Value() []int32 {
	if m != nil {
		return m.PathRepeatedSint32Value
	}
	return nil
}

func (m *ABitOfEverythingRepeated) GetPathRepeatedSint64Value() []int64 {
	if m != nil {
		return m.PathRepeatedSint64Value
	}
	return nil
}

type Body struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_0880245b62d9020b, []int{2}
}
func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (dst *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(dst, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MessageWithBody struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *Body    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWithBody) Reset()         { *m = MessageWithBody{} }
func (m *MessageWithBody) String() string { return proto.CompactTextString(m) }
func (*MessageWithBody) ProtoMessage()    {}
func (*MessageWithBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_0880245b62d9020b, []int{3}
}
func (m *MessageWithBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithBody.Unmarshal(m, b)
}
func (m *MessageWithBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithBody.Marshal(b, m, deterministic)
}
func (dst *MessageWithBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithBody.Merge(dst, src)
}
func (m *MessageWithBody) XXX_Size() int {
	return xxx_messageInfo_MessageWithBody.Size(m)
}
func (m *MessageWithBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithBody.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithBody proto.InternalMessageInfo

func (m *MessageWithBody) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageWithBody) GetData() *Body {
	if m != nil {
		return m.Data
	}
	return nil
}

// UpdateV2Request request for update includes the message and the update mask
type UpdateV2Request struct {
	Abe                  *ABitOfEverything     `protobuf:"bytes,1,opt,name=abe,proto3" json:"abe,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateV2Request) Reset()         { *m = UpdateV2Request{} }
func (m *UpdateV2Request) String() string { return proto.CompactTextString(m) }
func (*UpdateV2Request) ProtoMessage()    {}
func (*UpdateV2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_0880245b62d9020b, []int{4}
}
func (m *UpdateV2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateV2Request.Unmarshal(m, b)
}
func (m *UpdateV2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateV2Request.Marshal(b, m, deterministic)
}
func (dst *UpdateV2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateV2Request.Merge(dst, src)
}
func (m *UpdateV2Request) XXX_Size() int {
	return xxx_messageInfo_UpdateV2Request.Size(m)
}
func (m *UpdateV2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateV2Request.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateV2Request proto.InternalMessageInfo

func (m *UpdateV2Request) GetAbe() *ABitOfEverything {
	if m != nil {
		return m.Abe
	}
	return nil
}

func (m *UpdateV2Request) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

func init() {
	proto.RegisterType((*ABitOfEverything)(nil), "grpc.gateway.examples.examplepb.ABitOfEverything")
	proto.RegisterMapType((map[string]NumericEnum)(nil), "grpc.gateway.examples.examplepb.ABitOfEverything.MapValueEntry")
	proto.RegisterMapType((map[string]*ABitOfEverything_Nested)(nil), "grpc.gateway.examples.examplepb.ABitOfEverything.MappedNestedValueEntry")
	proto.RegisterMapType((map[string]string)(nil), "grpc.gateway.examples.examplepb.ABitOfEverything.MappedStringValueEntry")
	proto.RegisterType((*ABitOfEverything_Nested)(nil), "grpc.gateway.examples.examplepb.ABitOfEverything.Nested")
	proto.RegisterType((*ABitOfEverythingRepeated)(nil), "grpc.gateway.examples.examplepb.ABitOfEverythingRepeated")
	proto.RegisterType((*Body)(nil), "grpc.gateway.examples.examplepb.Body")
	proto.RegisterType((*MessageWithBody)(nil), "grpc.gateway.examples.examplepb.MessageWithBody")
	proto.RegisterType((*UpdateV2Request)(nil), "grpc.gateway.examples.examplepb.UpdateV2Request")
	proto.RegisterEnum("grpc.gateway.examples.examplepb.NumericEnum", NumericEnum_name, NumericEnum_value)
	proto.RegisterEnum("grpc.gateway.examples.examplepb.ABitOfEverything_Nested_DeepEnum", ABitOfEverything_Nested_DeepEnum_name, ABitOfEverything_Nested_DeepEnum_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ABitOfEverythingServiceClient is the client API for ABitOfEverythingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ABitOfEverythingServiceClient interface {
	// Create a new ABitOfEverything
	//
	// This API creates a new ABitOfEverything
	Create(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	CreateBody(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	Lookup(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*ABitOfEverything, error)
	Update(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateV2(ctx context.Context, in *UpdateV2Request, opts ...grpc.CallOption) (*empty.Empty, error)
	PatchWithFieldMaskInBody(ctx context.Context, in *UpdateV2Request, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*empty.Empty, error)
	GetQuery(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*empty.Empty, error)
	GetRepeatedQuery(ctx context.Context, in *ABitOfEverythingRepeated, opts ...grpc.CallOption) (*ABitOfEverythingRepeated, error)
	// Echo allows posting a StringMessage value.
	//
	// It also exposes multiple bindings.
	//
	// This makes it useful when validating that the OpenAPI v2 API
	// description exposes documentation correctly on all paths
	// defined as additional_bindings in the proto.
	Echo(ctx context.Context, in *sub.StringMessage, opts ...grpc.CallOption) (*sub.StringMessage, error)
	DeepPathEcho(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	NoBindings(ctx context.Context, in *duration.Duration, opts ...grpc.CallOption) (*empty.Empty, error)
	Timeout(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	ErrorWithDetails(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GetMessageWithBody(ctx context.Context, in *MessageWithBody, opts ...grpc.CallOption) (*empty.Empty, error)
	PostWithEmptyBody(ctx context.Context, in *Body, opts ...grpc.CallOption) (*empty.Empty, error)
}

type aBitOfEverythingServiceClient struct {
	cc *grpc.ClientConn
}

func NewABitOfEverythingServiceClient(cc *grpc.ClientConn) ABitOfEverythingServiceClient {
	return &aBitOfEverythingServiceClient{cc}
}

func (c *aBitOfEverythingServiceClient) Create(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) CreateBody(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/CreateBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Lookup(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Lookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Update(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) UpdateV2(ctx context.Context, in *UpdateV2Request, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/UpdateV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) PatchWithFieldMaskInBody(ctx context.Context, in *UpdateV2Request, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/PatchWithFieldMaskInBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Delete(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) GetQuery(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) GetRepeatedQuery(ctx context.Context, in *ABitOfEverythingRepeated, opts ...grpc.CallOption) (*ABitOfEverythingRepeated, error) {
	out := new(ABitOfEverythingRepeated)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetRepeatedQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Echo(ctx context.Context, in *sub.StringMessage, opts ...grpc.CallOption) (*sub.StringMessage, error) {
	out := new(sub.StringMessage)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) DeepPathEcho(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/DeepPathEcho", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) NoBindings(ctx context.Context, in *duration.Duration, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/NoBindings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Timeout(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Timeout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) ErrorWithDetails(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/ErrorWithDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) GetMessageWithBody(ctx context.Context, in *MessageWithBody, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetMessageWithBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) PostWithEmptyBody(ctx context.Context, in *Body, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/PostWithEmptyBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ABitOfEverythingServiceServer is the server API for ABitOfEverythingService service.
type ABitOfEverythingServiceServer interface {
	// Create a new ABitOfEverything
	//
	// This API creates a new ABitOfEverything
	Create(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	CreateBody(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	Lookup(context.Context, *sub2.IdMessage) (*ABitOfEverything, error)
	Update(context.Context, *ABitOfEverything) (*empty.Empty, error)
	UpdateV2(context.Context, *UpdateV2Request) (*empty.Empty, error)
	PatchWithFieldMaskInBody(context.Context, *UpdateV2Request) (*empty.Empty, error)
	Delete(context.Context, *sub2.IdMessage) (*empty.Empty, error)
	GetQuery(context.Context, *ABitOfEverything) (*empty.Empty, error)
	GetRepeatedQuery(context.Context, *ABitOfEverythingRepeated) (*ABitOfEverythingRepeated, error)
	// Echo allows posting a StringMessage value.
	//
	// It also exposes multiple bindings.
	//
	// This makes it useful when validating that the OpenAPI v2 API
	// description exposes documentation correctly on all paths
	// defined as additional_bindings in the proto.
	Echo(context.Context, *sub.StringMessage) (*sub.StringMessage, error)
	DeepPathEcho(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	NoBindings(context.Context, *duration.Duration) (*empty.Empty, error)
	Timeout(context.Context, *empty.Empty) (*empty.Empty, error)
	ErrorWithDetails(context.Context, *empty.Empty) (*empty.Empty, error)
	GetMessageWithBody(context.Context, *MessageWithBody) (*empty.Empty, error)
	PostWithEmptyBody(context.Context, *Body) (*empty.Empty, error)
}

func RegisterABitOfEverythingServiceServer(s *grpc.Server, srv ABitOfEverythingServiceServer) {
	s.RegisterService(&_ABitOfEverythingService_serviceDesc, srv)
}

func _ABitOfEverythingService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Create(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_CreateBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).CreateBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/CreateBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).CreateBody(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sub2.IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Lookup(ctx, req.(*sub2.IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Update(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_UpdateV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).UpdateV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/UpdateV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).UpdateV2(ctx, req.(*UpdateV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_PatchWithFieldMaskInBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).PatchWithFieldMaskInBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/PatchWithFieldMaskInBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).PatchWithFieldMaskInBody(ctx, req.(*UpdateV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sub2.IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Delete(ctx, req.(*sub2.IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_GetQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).GetQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).GetQuery(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_GetRepeatedQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverythingRepeated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).GetRepeatedQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetRepeatedQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).GetRepeatedQuery(ctx, req.(*ABitOfEverythingRepeated))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sub.StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Echo(ctx, req.(*sub.StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_DeepPathEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).DeepPathEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/DeepPathEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).DeepPathEcho(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_NoBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(duration.Duration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).NoBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/NoBindings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).NoBindings(ctx, req.(*duration.Duration))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Timeout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Timeout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Timeout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Timeout(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_ErrorWithDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).ErrorWithDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/ErrorWithDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).ErrorWithDetails(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_GetMessageWithBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageWithBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).GetMessageWithBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetMessageWithBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).GetMessageWithBody(ctx, req.(*MessageWithBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_PostWithEmptyBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Body)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).PostWithEmptyBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/PostWithEmptyBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).PostWithEmptyBody(ctx, req.(*Body))
	}
	return interceptor(ctx, in, info, handler)
}

var _ABitOfEverythingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.examplepb.ABitOfEverythingService",
	HandlerType: (*ABitOfEverythingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ABitOfEverythingService_Create_Handler,
		},
		{
			MethodName: "CreateBody",
			Handler:    _ABitOfEverythingService_CreateBody_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _ABitOfEverythingService_Lookup_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ABitOfEverythingService_Update_Handler,
		},
		{
			MethodName: "UpdateV2",
			Handler:    _ABitOfEverythingService_UpdateV2_Handler,
		},
		{
			MethodName: "PatchWithFieldMaskInBody",
			Handler:    _ABitOfEverythingService_PatchWithFieldMaskInBody_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ABitOfEverythingService_Delete_Handler,
		},
		{
			MethodName: "GetQuery",
			Handler:    _ABitOfEverythingService_GetQuery_Handler,
		},
		{
			MethodName: "GetRepeatedQuery",
			Handler:    _ABitOfEverythingService_GetRepeatedQuery_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _ABitOfEverythingService_Echo_Handler,
		},
		{
			MethodName: "DeepPathEcho",
			Handler:    _ABitOfEverythingService_DeepPathEcho_Handler,
		},
		{
			MethodName: "NoBindings",
			Handler:    _ABitOfEverythingService_NoBindings_Handler,
		},
		{
			MethodName: "Timeout",
			Handler:    _ABitOfEverythingService_Timeout_Handler,
		},
		{
			MethodName: "ErrorWithDetails",
			Handler:    _ABitOfEverythingService_ErrorWithDetails_Handler,
		},
		{
			MethodName: "GetMessageWithBody",
			Handler:    _ABitOfEverythingService_GetMessageWithBody_Handler,
		},
		{
			MethodName: "PostWithEmptyBody",
			Handler:    _ABitOfEverythingService_PostWithEmptyBody_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/proto/examplepb/a_bit_of_everything.proto",
}

// CamelCaseServiceNameClient is the client API for CamelCaseServiceName service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CamelCaseServiceNameClient interface {
	Empty(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type camelCaseServiceNameClient struct {
	cc *grpc.ClientConn
}

func NewCamelCaseServiceNameClient(cc *grpc.ClientConn) CamelCaseServiceNameClient {
	return &camelCaseServiceNameClient{cc}
}

func (c *camelCaseServiceNameClient) Empty(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.camelCaseServiceName/Empty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CamelCaseServiceNameServer is the server API for CamelCaseServiceName service.
type CamelCaseServiceNameServer interface {
	Empty(context.Context, *empty.Empty) (*empty.Empty, error)
}

func RegisterCamelCaseServiceNameServer(s *grpc.Server, srv CamelCaseServiceNameServer) {
	s.RegisterService(&_CamelCaseServiceName_serviceDesc, srv)
}

func _CamelCaseServiceName_Empty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CamelCaseServiceNameServer).Empty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.camelCaseServiceName/Empty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CamelCaseServiceNameServer).Empty(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _CamelCaseServiceName_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.examplepb.camelCaseServiceName",
	HandlerType: (*CamelCaseServiceNameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Empty",
			Handler:    _CamelCaseServiceName_Empty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/proto/examplepb/a_bit_of_everything.proto",
}

// AnotherServiceWithNoBindingsClient is the client API for AnotherServiceWithNoBindings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnotherServiceWithNoBindingsClient interface {
	NoBindings(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type anotherServiceWithNoBindingsClient struct {
	cc *grpc.ClientConn
}

func NewAnotherServiceWithNoBindingsClient(cc *grpc.ClientConn) AnotherServiceWithNoBindingsClient {
	return &anotherServiceWithNoBindingsClient{cc}
}

func (c *anotherServiceWithNoBindingsClient) NoBindings(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.AnotherServiceWithNoBindings/NoBindings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnotherServiceWithNoBindingsServer is the server API for AnotherServiceWithNoBindings service.
type AnotherServiceWithNoBindingsServer interface {
	NoBindings(context.Context, *empty.Empty) (*empty.Empty, error)
}

func RegisterAnotherServiceWithNoBindingsServer(s *grpc.Server, srv AnotherServiceWithNoBindingsServer) {
	s.RegisterService(&_AnotherServiceWithNoBindings_serviceDesc, srv)
}

func _AnotherServiceWithNoBindings_NoBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnotherServiceWithNoBindingsServer).NoBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.AnotherServiceWithNoBindings/NoBindings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnotherServiceWithNoBindingsServer).NoBindings(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnotherServiceWithNoBindings_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.examplepb.AnotherServiceWithNoBindings",
	HandlerType: (*AnotherServiceWithNoBindingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NoBindings",
			Handler:    _AnotherServiceWithNoBindings_NoBindings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/proto/examplepb/a_bit_of_everything.proto",
}

func init() {
	proto.RegisterFile("examples/proto/examplepb/a_bit_of_everything.proto", fileDescriptor_a_bit_of_everything_0880245b62d9020b)
}

var fileDescriptor_a_bit_of_everything_0880245b62d9020b = []byte{
	// 3269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x3a, 0x4b, 0x70, 0xdb, 0xc6,
	0xd9, 0x02, 0x41, 0xbd, 0x56, 0x2f, 0x6a, 0x65, 0xcb, 0x14, 0x2d, 0x47, 0x6b, 0xd8, 0x49, 0x60,
	0xc6, 0x24, 0x24, 0x48, 0x76, 0x64, 0x66, 0x12, 0xff, 0xa4, 0x1e, 0xb6, 0xfc, 0x90, 0x15, 0xd8,
	0xf1, 0x9f, 0x71, 0xec, 0x68, 0x40, 0x72, 0x29, 0xc2, 0x22, 0x1e, 0x01, 0x16, 0xb2, 0xf9, 0xf3,
	0xe7, 0xff, 0x67, 0xda, 0x4e, 0x3b, 0x6d, 0x0e, 0x9d, 0x61, 0xda, 0xe9, 0xf4, 0x31, 0xbd, 0xf4,
	0x9a, 0x6b, 0x4f, 0xe9, 0xb4, 0xbd, 0xf7, 0xe6, 0x76, 0x7a, 0xeb, 0xa9, 0x3d, 0xf7, 0xd2, 0x99,
	0xcc, 0xf4, 0xd0, 0x4e, 0x07, 0x0b, 0x80, 0x04, 0x40, 0xd2, 0x32, 0xed, 0x4c, 0x2e, 0x32, 0x76,
	0xf7, 0x7b, 0x7f, 0xdf, 0x7e, 0x8f, 0xa5, 0x81, 0x88, 0x9f, 0xca, 0xaa, 0x51, 0xc3, 0x96, 0x60,
	0x98, 0x3a, 0xd1, 0x05, 0x6f, 0x69, 0x14, 0x05, 0x79, 0xbf, 0xa8, 0x90, 0x7d, 0xbd, 0xb2, 0x8f,
	0x8f, 0xb0, 0x59, 0x27, 0x55, 0x45, 0x3b, 0xc8, 0x52, 0x18, 0xb8, 0x74, 0x60, 0x1a, 0xa5, 0xec,
	0x81, 0x4c, 0xf0, 0x13, 0xb9, 0x9e, 0xf5, 0x09, 0x64, 0xdb, 0xa8, 0xa9, 0xc5, 0x03, 0x5d, 0x3f,
	0xa8, 0x61, 0x41, 0x36, 0x14, 0x41, 0xd6, 0x34, 0x9d, 0xc8, 0x44, 0xd1, 0x35, 0xcb, 0x45, 0x4f,
	0x21, 0xef, 0x94, 0xae, 0x8a, 0x76, 0x45, 0xa8, 0x28, 0xb8, 0x56, 0xde, 0x57, 0x65, 0xeb, 0xd0,
	0x83, 0x38, 0x1d, 0x85, 0xc0, 0xaa, 0x41, 0xea, 0xde, 0xe1, 0x6b, 0xd1, 0xc3, 0xb2, 0x6d, 0x52,
	0xfa, 0xde, 0xf9, 0x9b, 0x11, 0x8d, 0x0c, 0x99, 0x54, 0xb1, 0x66, 0xab, 0xf4, 0x63, 0xdf, 0xf9,
	0xf2, 0xe5, 0x88, 0x00, 0x5a, 0x76, 0x51, 0x50, 0xb1, 0x65, 0xc9, 0x07, 0xd8, 0x83, 0x38, 0xdb,
	0x0d, 0x21, 0x46, 0x40, 0x96, 0xa2, 0xd2, 0x10, 0x45, 0xc5, 0x16, 0x91, 0x55, 0xc3, 0x03, 0xb8,
	0x48, 0xff, 0x29, 0x65, 0x0e, 0xb0, 0x96, 0xb1, 0x9e, 0xc8, 0x07, 0x07, 0xd8, 0x14, 0x74, 0x83,
	0xda, 0xa3, 0xdb, 0x36, 0xdc, 0x4f, 0x4e, 0x83, 0x44, 0xbe, 0xa0, 0x90, 0x3b, 0x95, 0xad, 0xb6,
	0xd5, 0xe1, 0x23, 0x30, 0x65, 0x29, 0xda, 0x41, 0x0d, 0xef, 0x6b, 0xd8, 0x22, 0xb8, 0x9c, 0x5c,
	0x40, 0x0c, 0x3f, 0x21, 0xae, 0x67, 0x8f, 0xf1, 0x43, 0x36, 0x4a, 0x29, 0xbb, 0x4b, 0xf1, 0xa5,
	0x49, 0x97, 0x9c, 0xbb, 0x82, 0x55, 0x10, 0xb7, 0x6d, 0xa5, 0x9c, 0x64, 0x10, 0xc3, 0x8f, 0x17,
	0xee, 0xb5, 0xf2, 0xef, 0x7f, 0xca, 0x30, 0x3f, 0x60, 0x6e, 0x7e, 0x24, 0x67, 0x2a, 0xf9, 0xcc,
	0xf6, 0x72, 0xe6, 0xca, 0xa3, 0xc6, 0x7a, 0x33, 0x13, 0x5c, 0xae, 0x0d, 0xb2, 0x5c, 0x11, 0x9b,
	0x12, 0xe5, 0x00, 0xf7, 0xc0, 0x88, 0xa7, 0x41, 0x0c, 0xb1, 0xaf, 0xa4, 0x81, 0x47, 0x07, 0xde,
	0x00, 0x13, 0x95, 0x9a, 0x2e, 0x93, 0xfd, 0x23, 0xb9, 0x66, 0xe3, 0x24, 0x8b, 0x18, 0x3e, 0x56,
	0xb8, 0xd0, 0xca, 0xbf, 0x21, 0xce, 0x6e, 0x3b, 0xfb, 0x88, 0xee, 0x23, 0x1a, 0x61, 0x39, 0x76,
	0x39, 0x2b, 0x3e, 0x63, 0x82, 0x08, 0x12, 0xa0, 0x8b, 0xfb, 0xce, 0x37, 0x3c, 0x0b, 0x26, 0xcb,
	0xba, 0x5d, 0xac, 0x61, 0x8f, 0x58, 0x1c, 0x31, 0x3c, 0x23, 0x4d, 0xb8, 0x7b, 0x2e, 0xc8, 0x12,
	0x98, 0x50, 0x34, 0x72, 0x79, 0xcd, 0x83, 0x18, 0x46, 0x0c, 0xcf, 0x4a, 0x80, 0x6e, 0xb5, 0x69,
	0xd8, 0x41, 0x88, 0x11, 0xc4, 0xf0, 0x71, 0x69, 0xc2, 0x0e, 0x80, 0xb8, 0x34, 0x56, 0x45, 0x0f,
	0x62, 0x14, 0x31, 0xfc, 0x30, 0xa5, 0xb1, 0x2a, 0xba, 0x00, 0xe7, 0xc0, 0x54, 0x45, 0x79, 0x8a,
	0xcb, 0x6d, 0x22, 0x63, 0x88, 0xe1, 0x47, 0xa4, 0x49, 0x6f, 0x33, 0x0c, 0xd4, 0xa6, 0x33, 0x8e,
	0x18, 0x7e, 0xd4, 0x03, 0xf2, 0x29, 0x9d, 0x01, 0xa0, 0xa8, 0xeb, 0x35, 0x0f, 0x02, 0x20, 0x86,
	0x1f, 0x93, 0xc6, 0x9d, 0x9d, 0xb6, 0xb0, 0x16, 0x31, 0x15, 0xed, 0xc0, 0x03, 0x98, 0x70, 0x02,
	0x40, 0x9a, 0x70, 0xf7, 0xda, 0xc2, 0x16, 0xeb, 0x04, 0x5b, 0x1e, 0xc4, 0x19, 0xc4, 0xf0, 0x93,
	0x12, 0xa0, 0x5b, 0x21, 0x85, 0xdb, 0x62, 0x4c, 0x21, 0x86, 0x9f, 0x72, 0x15, 0xf6, 0xa5, 0xb8,
	0x09, 0x80, 0x73, 0xeb, 0x3c, 0x80, 0x69, 0xc4, 0xf0, 0xd3, 0xe2, 0xc5, 0x63, 0x3d, 0xbf, 0x6b,
	0xab, 0xd8, 0x54, 0x4a, 0x5b, 0x9a, 0xad, 0x4a, 0xe3, 0x0e, 0xbe, 0x4b, 0x6c, 0x0f, 0xcc, 0xb4,
	0xef, 0xb1, 0x47, 0xf1, 0x35, 0x4a, 0x91, 0xef, 0x43, 0xd1, 0xbf, 0xfe, 0xd9, 0x3d, 0x99, 0x54,
	0x29, 0xb5, 0x29, 0xc3, 0xfb, 0x72, 0x29, 0x5a, 0x60, 0xde, 0x0d, 0xa6, 0xfd, 0x28, 0xe1, 0x25,
	0x4a, 0xf8, 0xbd, 0xe3, 0x08, 0xdf, 0x76, 0x13, 0x82, 0x4f, 0xdf, 0x0b, 0xd1, 0x36, 0xbb, 0x39,
	0x2d, 0xb4, 0x76, 0x99, 0xbe, 0x0e, 0xa6, 0xad, 0xb0, 0xff, 0x66, 0x10, 0xc3, 0xcf, 0x48, 0x53,
	0x56, 0xc8, 0x81, 0x6d, 0xb0, 0x76, 0x2c, 0x24, 0x10, 0xc3, 0x27, 0x7c, 0xb0, 0x40, 0xd4, 0x59,
	0x41, 0x27, 0xcc, 0x22, 0x86, 0x9f, 0x95, 0x26, 0xac, 0x80, 0x13, 0x3c, 0x90, 0x36, 0x1d, 0x88,
	0x18, 0x1e, 0xba, 0x20, 0x3e, 0x15, 0x11, 0x9c, 0x34, 0xb1, 0x81, 0x65, 0xc7, 0x14, 0xa1, 0xb8,
	0x98, 0x43, 0x2c, 0x3f, 0x2e, 0xcd, 0xf9, 0x87, 0x77, 0x03, 0xf1, 0x71, 0x05, 0x4c, 0xe8, 0x1a,
	0x76, 0x8a, 0x84, 0x93, 0xa1, 0x93, 0x27, 0x68, 0x62, 0x9a, 0xcf, 0xba, 0x49, 0x31, 0xeb, 0x27,
	0xc5, 0xec, 0x96, 0x73, 0x7a, 0x7d, 0x48, 0x02, 0x14, 0x98, 0xae, 0xe0, 0x39, 0x30, 0xe9, 0xa2,
	0xba, 0xbc, 0x92, 0x27, 0x9d, 0xe8, 0xbb, 0x3e, 0x24, 0xb9, 0x04, 0x5d, 0x26, 0xf0, 0x21, 0x18,
	0x57, 0x65, 0xc3, 0x93, 0x63, 0x9e, 0x26, 0x8d, 0xab, 0x83, 0x27, 0x8d, 0xdb, 0xb2, 0x41, 0xc5,
	0xdd, 0xd2, 0x88, 0x59, 0x97, 0xc6, 0x54, 0x6f, 0x09, 0x9f, 0x82, 0x39, 0x55, 0x36, 0x8c, 0xa8,
	0xbe, 0xa7, 0x28, 0x9f, 0xeb, 0x2f, 0xc5, 0xc7, 0x08, 0xd9, 0xc7, 0x65, 0x38, 0xab, 0x46, 0xf7,
	0x03, 0x9c, 0xbd, 0xd8, 0x73, 0x39, 0x27, 0x5f, 0x8d, 0xb3, 0x1b, 0x79, 0xdd, 0x9c, 0x03, 0xfb,
	0x30, 0x07, 0x92, 0x9a, 0xae, 0x6d, 0xe8, 0xda, 0x11, 0xd6, 0x9c, 0xca, 0x23, 0xd7, 0x76, 0x65,
	0xd5, 0x4d, 0x6f, 0xc9, 0x14, 0x4d, 0x00, 0x7d, 0xcf, 0xe1, 0x06, 0x98, 0x69, 0x97, 0x37, 0x4f,
	0xe2, 0xd3, 0xd4, 0xe3, 0xa9, 0x2e, 0x8f, 0xdf, 0xf3, 0xe1, 0xa4, 0xe9, 0x36, 0x8a, 0x4b, 0xe4,
	0x21, 0x68, 0x47, 0x52, 0xf0, 0xb2, 0x2d, 0x22, 0x76, 0xe0, 0xbc, 0x30, 0xeb, 0x13, 0xea, 0x5c,
	0xac, 0x2f, 0x18, 0x90, 0x0c, 0x93, 0xef, 0x14, 0xd9, 0x24, 0x1a, 0x9c, 0x47, 0x61, 0xb3, 0x95,
	0xcf, 0xa7, 0x4f, 0x4b, 0x1e, 0x49, 0xa4, 0xb9, 0x47, 0xc8, 0x21, 0x8d, 0x88, 0x42, 0x6a, 0x58,
	0xe4, 0x7a, 0x1f, 0x96, 0xb1, 0x55, 0x32, 0x15, 0x5a, 0xe9, 0xb3, 0xd2, 0x7c, 0x50, 0xd2, 0x7c,
	0x5b, 0x22, 0xf8, 0x23, 0x06, 0x9c, 0xec, 0x18, 0x21, 0x28, 0xeb, 0xd9, 0xc1, 0xf3, 0x64, 0x41,
	0x6c, 0xe5, 0x85, 0x34, 0xdc, 0xed, 0x16, 0x71, 0x61, 0xb7, 0xaf, 0x64, 0x73, 0xed, 0xdc, 0x1a,
	0x10, 0xeb, 0x08, 0xa4, 0xa2, 0xa9, 0x20, 0x20, 0x1a, 0xe7, 0xe4, 0x83, 0xc2, 0x7a, 0x2b, 0x7f,
	0x29, 0x7d, 0xb2, 0xad, 0xbb, 0x0b, 0xe6, 0xf1, 0x5b, 0x8c, 0x6e, 0x87, 0x58, 0x26, 0xc3, 0x99,
	0x24, 0xc0, 0xf7, 0xb7, 0x4c, 0x80, 0xb1, 0x77, 0x33, 0x02, 0x8c, 0xcf, 0xbd, 0x5a, 0xd7, 0x50,
	0xd8, 0x6e, 0xe5, 0x37, 0xd2, 0x1d, 0xd9, 0x5c, 0x06, 0x48, 0x2f, 0x3e, 0xc6, 0x25, 0xe2, 0x49,
	0x7e, 0xae, 0xcf, 0x69, 0x6f, 0x05, 0x5c, 0xba, 0x01, 0x05, 0x7e, 0xce, 0x80, 0xd9, 0x6e, 0xb9,
	0xcf, 0xbf, 0x5a, 0xbf, 0x56, 0x58, 0x6b, 0xe5, 0x57, 0xd2, 0x73, 0xbb, 0x3d, 0xc4, 0x4d, 0xed,
	0xf6, 0x97, 0x32, 0xa1, 0x45, 0xa4, 0x4b, 0xfd, 0x85, 0x01, 0x23, 0x5e, 0xd3, 0x07, 0x41, 0x5c,
	0x93, 0x55, 0xec, 0x36, 0x7d, 0x12, 0xfd, 0x86, 0xf3, 0x60, 0x44, 0x56, 0x75, 0x5b, 0x23, 0xc9,
	0x18, 0xad, 0xe2, 0xde, 0x0a, 0xaa, 0x20, 0xa6, 0x1f, 0xd2, 0xde, 0x6a, 0x5a, 0xcc, 0xbf, 0xac,
	0x12, 0xd9, 0x4d, 0x8c, 0x0d, 0x1a, 0xa5, 0xa9, 0x56, 0xfe, 0x94, 0x78, 0xd2, 0x5f, 0x86, 0x65,
	0x8e, 0xe9, 0x87, 0xdc, 0x12, 0x18, 0xf3, 0x0f, 0xe1, 0x38, 0x18, 0xde, 0xce, 0xdf, 0xba, 0xbb,
	0x95, 0x18, 0x82, 0x63, 0x20, 0x7e, 0x4f, 0xfa, 0x60, 0x2b, 0xc1, 0xe4, 0x4e, 0xb5, 0xf2, 0x27,
	0x44, 0x08, 0x13, 0x0d, 0xc4, 0xe9, 0x87, 0x5c, 0x0e, 0x71, 0xce, 0x3e, 0x87, 0x9a, 0x29, 0x05,
	0x4c, 0x85, 0x52, 0x3d, 0x4c, 0x00, 0xf6, 0x10, 0xd7, 0x3d, 0x25, 0x9d, 0x4f, 0x58, 0x00, 0xc3,
	0x6e, 0xbe, 0x89, 0xbd, 0x44, 0x1f, 0xe2, 0xa2, 0xe6, 0x62, 0xeb, 0x4c, 0x6a, 0x13, 0xcc, 0xf7,
	0xce, 0xf6, 0x3d, 0x78, 0x9e, 0x08, 0xf2, 0x1c, 0x0f, 0x52, 0xf9, 0x3f, 0x9f, 0x4a, 0x34, 0x73,
	0xf7, 0xa0, 0xb2, 0x1b, 0xa4, 0xf2, 0x2a, 0xbd, 0x73, 0x87, 0x7f, 0xee, 0xa7, 0xb1, 0x56, 0xfe,
	0xc7, 0x31, 0xf0, 0x1d, 0x26, 0x3d, 0x97, 0x47, 0x45, 0x85, 0x20, 0xbd, 0x82, 0x3a, 0xe3, 0x9e,
	0xb8, 0xb3, 0xa3, 0x11, 0xbf, 0x0a, 0xd4, 0x51, 0x49, 0x57, 0x8d, 0x9a, 0x52, 0xa2, 0x97, 0xc3,
	0x1b, 0x82, 0x10, 0xa9, 0x1b, 0x18, 0x11, 0x1d, 0x95, 0xf4, 0x23, 0x6c, 0x22, 0x55, 0xd6, 0xea,
	0xa8, 0x82, 0x65, 0x62, 0x9b, 0xd8, 0x72, 0x68, 0xed, 0xf9, 0xe5, 0xe0, 0x19, 0x43, 0x27, 0x80,
	0x67, 0x4c, 0xb0, 0x7f, 0x7e, 0xc6, 0x84, 0x1a, 0xee, 0xf4, 0x7d, 0x70, 0x7e, 0x5b, 0xd1, 0xca,
	0x48, 0xb7, 0x09, 0x52, 0x75, 0x13, 0x23, 0xb9, 0xe8, 0x7c, 0x76, 0xcd, 0x43, 0xd9, 0x2a, 0x21,
	0x86, 0x95, 0x13, 0x84, 0x03, 0x85, 0x54, 0xed, 0x62, 0xb6, 0xa4, 0xab, 0x82, 0x63, 0x8c, 0x0c,
	0x2e, 0xe9, 0x56, 0xdd, 0x22, 0xd8, 0x5b, 0x7a, 0xb6, 0x11, 0xd7, 0xa0, 0xd8, 0x40, 0x9c, 0xc3,
	0xdf, 0x09, 0x96, 0xe5, 0x52, 0x65, 0xf5, 0xf2, 0x0a, 0x5e, 0xc9, 0xac, 0x15, 0xd7, 0xd6, 0x32,
	0x6b, 0xeb, 0xab, 0xe5, 0x8c, 0xbc, 0x72, 0xe9, 0x4a, 0xe6, 0xd2, 0x5a, 0x59, 0x2e, 0x96, 0x2b,
	0x6f, 0xe3, 0xf5, 0x95, 0x35, 0x0e, 0x35, 0x0b, 0x53, 0x7e, 0x6b, 0x43, 0x85, 0xe3, 0xfe, 0x3d,
	0x06, 0x92, 0x51, 0x49, 0xfc, 0x5c, 0x01, 0xaf, 0x80, 0x05, 0xda, 0x3c, 0xb6, 0x73, 0x57, 0x70,
	0x28, 0x61, 0x10, 0xcb, 0xc7, 0xa4, 0x79, 0x07, 0xc0, 0x47, 0xd8, 0xee, 0x4c, 0x1d, 0xef, 0x80,
	0x54, 0x18, 0x35, 0x34, 0x83, 0x38, 0x73, 0x12, 0x23, 0x9d, 0x0a, 0xe2, 0x6e, 0x06, 0xe6, 0x91,
	0x2e, 0xbe, 0xc1, 0x16, 0x8f, 0x45, 0x2c, 0xcf, 0x86, 0xf9, 0xee, 0x74, 0xba, 0xbd, 0x2e, 0xbe,
	0xa1, 0xb9, 0x25, 0x8e, 0x58, 0x3e, 0x1e, 0xe6, 0xfb, 0x41, 0xa0, 0x55, 0xec, 0xc5, 0xb7, 0xdd,
	0x7d, 0x0e, 0x23, 0x96, 0x1f, 0xee, 0xe2, 0xeb, 0x37, 0xa2, 0xef, 0x82, 0xd3, 0x11, 0x53, 0x85,
	0xfa, 0xdb, 0x11, 0xc4, 0xf2, 0x23, 0x52, 0x32, 0x64, 0xac, 0x60, 0xab, 0xdb, 0x1b, 0x3d, 0x30,
	0x4d, 0xb1, 0xfc, 0x68, 0x0f, 0x74, 0x9f, 0xfb, 0xdb, 0x20, 0x19, 0x46, 0x0f, 0xcc, 0x47, 0x63,
	0x88, 0xe5, 0xc7, 0xa4, 0x93, 0x41, 0xdc, 0x42, 0x7b, 0x56, 0xea, 0x32, 0x57, 0xa8, 0x63, 0x1c,
	0xa7, 0x1d, 0x72, 0xc8, 0x5c, 0xe1, 0x2e, 0x39, 0x62, 0xae, 0xe0, 0x4c, 0x05, 0x10, 0xcb, 0x4f,
	0x86, 0xcd, 0x55, 0xe8, 0xcc, 0x57, 0x3d, 0xdd, 0xd4, 0x56, 0x77, 0x02, 0xb1, 0xfc, 0x54, 0xb7,
	0x9b, 0x7c, 0x6d, 0x71, 0x54, 0xdb, 0x40, 0xbf, 0x35, 0xf9, 0x12, 0xfd, 0x56, 0xc8, 0x36, 0x9d,
	0x9e, 0xeb, 0x2a, 0x58, 0x8c, 0xd8, 0x26, 0xec, 0x94, 0x29, 0xc4, 0xf2, 0x33, 0xd2, 0x42, 0xc8,
	0x3a, 0xa1, 0x31, 0xa7, 0x0f, 0x81, 0x76, 0x50, 0x4c, 0x23, 0x96, 0x4f, 0xf4, 0x22, 0xd0, 0x37,
	0x98, 0x43, 0xe3, 0xd0, 0x0c, 0x62, 0xf9, 0xd9, 0x88, 0x77, 0x02, 0x56, 0xea, 0x89, 0x1c, 0x18,
	0xb8, 0x58, 0x1e, 0x76, 0x23, 0x7b, 0x9c, 0x73, 0xd5, 0x56, 0x1e, 0x8b, 0x25, 0x28, 0x37, 0x10,
	0xd7, 0x2f, 0xb0, 0xb8, 0x1c, 0xfa, 0x88, 0x98, 0x36, 0xbe, 0x88, 0xdc, 0xbf, 0x15, 0xb9, 0x66,
	0x79, 0x8b, 0x47, 0x17, 0xa3, 0x68, 0x01, 0xb9, 0x1d, 0xbc, 0x95, 0x8b, 0x48, 0xbc, 0x88, 0x56,
	0x1f, 0xa1, 0x26, 0x97, 0x02, 0xf1, 0x82, 0x5e, 0xae, 0xf7, 0xaa, 0xdc, 0xdc, 0x43, 0x30, 0xe3,
	0x4d, 0xa1, 0xff, 0xad, 0x90, 0x2a, 0x05, 0x9b, 0x06, 0x31, 0xff, 0x4d, 0x47, 0x8a, 0x29, 0x4e,
	0x8a, 0x8a, 0x97, 0x65, 0x22, 0x7b, 0xd5, 0xe3, 0xf5, 0x63, 0xfd, 0xee, 0x10, 0x91, 0x28, 0x0a,
	0xf7, 0x39, 0x03, 0x66, 0x3e, 0x30, 0xca, 0x32, 0xc1, 0xf7, 0x45, 0x09, 0x7f, 0x62, 0x63, 0x8b,
	0xc0, 0x0d, 0xc0, 0xca, 0x45, 0x57, 0x88, 0x09, 0x71, 0x65, 0xe0, 0x5a, 0x24, 0x39, 0xd8, 0xf0,
	0x1d, 0x30, 0x61, 0x53, 0xba, 0xf4, 0xf1, 0xcf, 0x13, 0xad, 0x7b, 0x96, 0xd8, 0x56, 0x70, 0xad,
	0x7c, 0x5b, 0xb6, 0x0e, 0x25, 0xe0, 0x82, 0x3b, 0xdf, 0x69, 0x04, 0x26, 0x02, 0xb1, 0xe9, 0xb4,
	0x07, 0x0f, 0xb6, 0xa4, 0x3b, 0x89, 0x21, 0x38, 0x0a, 0xd8, 0x3b, 0xbb, 0x5b, 0x09, 0x46, 0xfc,
	0xe2, 0x0c, 0x38, 0x15, 0x65, 0x7c, 0x17, 0x9b, 0x47, 0x4a, 0x09, 0xc3, 0xbf, 0xb3, 0x60, 0x64,
	0xc3, 0x74, 0x6c, 0x0e, 0x07, 0x97, 0x3e, 0x35, 0x38, 0x0a, 0xf7, 0xaf, 0xd8, 0xb7, 0xfe, 0xf8,
	0xb7, 0xcf, 0x63, 0x5f, 0xc5, 0xb8, 0x7f, 0xc4, 0x84, 0xa3, 0x15, 0xff, 0xa1, 0xb5, 0xd7, 0x33,
	0xab, 0xd0, 0x08, 0x94, 0x8f, 0xa6, 0xd0, 0x08, 0x56, 0x84, 0xa6, 0xd0, 0x08, 0x44, 0x67, 0x53,
	0xb0, 0xb0, 0x21, 0x9b, 0x32, 0xd1, 0x4d, 0xa1, 0x61, 0x87, 0x0e, 0x1a, 0x81, 0x48, 0x6a, 0x0a,
	0x8d, 0xd0, 0x85, 0xf2, 0xd7, 0x81, 0xf3, 0x4e, 0xb8, 0x36, 0x85, 0x46, 0x30, 0xb7, 0xbd, 0x6b,
	0x11, 0xd3, 0x30, 0x71, 0x45, 0x79, 0x2a, 0xa4, 0x9b, 0x2e, 0x93, 0x00, 0x9a, 0x15, 0xa5, 0x63,
	0x45, 0x19, 0x59, 0x11, 0x84, 0xb0, 0x90, 0xfd, 0x46, 0xcd, 0xa6, 0xd0, 0xe8, 0xe4, 0xaa, 0xa6,
	0xd0, 0x88, 0x3c, 0xcd, 0x38, 0x98, 0x3d, 0xdf, 0x6c, 0x42, 0x78, 0x81, 0x16, 0xbc, 0x09, 0x7f,
	0xc9, 0x00, 0xe0, 0x3a, 0x9c, 0x5e, 0x8f, 0x6f, 0xc6, 0xe9, 0x69, 0xea, 0xf3, 0xf3, 0xdc, 0xd2,
	0x31, 0x1e, 0xcf, 0x31, 0x69, 0xf8, 0xbf, 0x60, 0xe4, 0x96, 0xae, 0x1f, 0xda, 0x06, 0x9c, 0xc9,
	0x5a, 0x76, 0x51, 0xcc, 0xee, 0x94, 0xbd, 0x3b, 0xfd, 0x32, 0x9c, 0xb3, 0x94, 0x33, 0x0f, 0xdf,
	0x38, 0x36, 0xd6, 0x9c, 0xbe, 0xa8, 0x09, 0xbf, 0xcb, 0x80, 0x11, 0xf7, 0x8e, 0xbf, 0x8c, 0x69,
	0xfa, 0xbc, 0xf8, 0x70, 0x2b, 0x54, 0x8a, 0xb7, 0x52, 0x2f, 0x28, 0x85, 0x63, 0x86, 0xdf, 0x33,
	0x60, 0xcc, 0x4f, 0x36, 0x70, 0xf9, 0x58, 0x51, 0x22, 0x79, 0xa9, 0xaf, 0x24, 0x8f, 0xa9, 0x24,
	0xe5, 0x54, 0x5a, 0x38, 0x12, 0x9f, 0x2f, 0x89, 0x5c, 0xc4, 0x59, 0x57, 0x1a, 0x27, 0x47, 0x3d,
	0x58, 0x11, 0x07, 0x45, 0x81, 0xbf, 0x60, 0x40, 0x72, 0x4f, 0x26, 0xa5, 0xaa, 0x93, 0x8c, 0xdb,
	0xc9, 0x6b, 0x47, 0xa3, 0x81, 0xf7, 0xf5, 0xa9, 0x74, 0x99, 0xaa, 0xb4, 0x2c, 0xbe, 0x25, 0x1c,
	0x89, 0xf2, 0x8b, 0x0a, 0xc8, 0xa4, 0xe1, 0x0f, 0x19, 0x30, 0xb2, 0x89, 0x6b, 0x98, 0xe0, 0xee,
	0x48, 0xeb, 0xc7, 0xeb, 0x61, 0x2b, 0xff, 0x56, 0xf1, 0x02, 0x98, 0x06, 0x20, 0x6f, 0x28, 0x37,
	0x71, 0x3d, 0x6f, 0x93, 0x2a, 0x1c, 0x02, 0xa7, 0xc0, 0xc8, 0x1d, 0xe7, 0x53, 0x84, 0x53, 0x20,
	0x6e, 0x62, 0xb9, 0x0c, 0x86, 0x9f, 0x98, 0x0a, 0xc1, 0x6e, 0xf0, 0xa5, 0x5f, 0x34, 0xf8, 0xfe,
	0xca, 0x80, 0xb1, 0x6b, 0x98, 0xbc, 0x6f, 0x63, 0xb3, 0xfe, 0x75, 0x86, 0xdf, 0x67, 0x4c, 0x2b,
	0x7f, 0x8f, 0xdb, 0x05, 0x8b, 0xbd, 0xc6, 0x8a, 0x36, 0xc3, 0x01, 0xc7, 0x89, 0x0f, 0x99, 0xe2,
	0x10, 0xd5, 0x2f, 0x0b, 0x2f, 0x1e, 0xa7, 0xdf, 0x27, 0x0e, 0x03, 0x5f, 0xcb, 0xcf, 0x86, 0x41,
	0xe2, 0x1a, 0x26, 0x7e, 0x17, 0xe1, 0x32, 0xbf, 0x32, 0x78, 0xe9, 0xf4, 0xf0, 0x53, 0x2f, 0x8f,
	0xca, 0x7d, 0x1a, 0xa7, 0x1a, 0xfc, 0x93, 0x85, 0x5f, 0xb1, 0xc7, 0xe8, 0xd0, 0x6e, 0x4d, 0xbc,
	0x24, 0xdc, 0x6b, 0xc4, 0x69, 0x46, 0xcf, 0x22, 0x15, 0xab, 0xef, 0x8c, 0xd2, 0x75, 0x66, 0x3f,
	0xef, 0x30, 0x5c, 0x49, 0x9e, 0x33, 0x45, 0xf4, 0x3e, 0xed, 0x8b, 0x1b, 0xaa, 0x7d, 0xfd, 0xbb,
	0xfc, 0x6e, 0xbc, 0x4e, 0x17, 0xdf, 0x53, 0x91, 0xbe, 0x0c, 0xbb, 0x4b, 0x5b, 0x9f, 0xd6, 0xb9,
	0xcf, 0x71, 0x5f, 0x3d, 0xad, 0xe7, 0x71, 0x0d, 0x95, 0x5e, 0xf8, 0x69, 0x1c, 0xc4, 0xb7, 0x4a,
	0x55, 0x1d, 0xf6, 0xfb, 0xe1, 0xc4, 0xb2, 0x8b, 0x59, 0x77, 0x88, 0xf1, 0x93, 0xc3, 0x0b, 0x43,
	0x72, 0xbf, 0x62, 0x5b, 0xf9, 0xdf, 0xc4, 0xc0, 0x24, 0x2e, 0x55, 0x75, 0x64, 0xb9, 0x2d, 0x17,
	0x18, 0xa3, 0x2b, 0xd3, 0x28, 0xc1, 0xd9, 0xbb, 0xb6, 0xaa, 0xca, 0x66, 0x3d, 0x87, 0xb6, 0xbc,
	0xad, 0x54, 0x62, 0xb3, 0xf3, 0x0c, 0x44, 0x77, 0xb9, 0x4d, 0x00, 0xc3, 0xd7, 0x96, 0x4a, 0x3b,
	0xe0, 0x65, 0xbd, 0x71, 0x05, 0xb0, 0xe2, 0xf2, 0x32, 0x14, 0xb9, 0x65, 0x90, 0x90, 0x0d, 0xf7,
	0xfd, 0x42, 0xd1, 0x35, 0xe1, 0xb1, 0xa5, 0x6b, 0x70, 0xb1, 0xc1, 0xf9, 0x9d, 0x36, 0x47, 0xaa,
	0x18, 0x29, 0x9a, 0x61, 0x7b, 0x3f, 0x19, 0x72, 0xcd, 0x1b, 0x57, 0x01, 0x7b, 0x69, 0x79, 0x15,
	0xae, 0x83, 0xcb, 0x12, 0x26, 0xb6, 0xa9, 0xe1, 0x32, 0x7a, 0x52, 0xc5, 0x1a, 0x72, 0x20, 0x4d,
	0x6c, 0xe9, 0xb6, 0x59, 0xc2, 0x48, 0xb1, 0x10, 0xc1, 0xaa, 0xa1, 0x9b, 0xb2, 0xa9, 0xd4, 0xea,
	0xc8, 0xd6, 0xe4, 0x23, 0x59, 0xa9, 0xc9, 0xc5, 0x1a, 0xce, 0xde, 0x78, 0x07, 0xb0, 0x6b, 0xcb,
	0x6b, 0x70, 0x0d, 0xa4, 0x9f, 0x43, 0xa0, 0xac, 0x63, 0x0b, 0x69, 0x3a, 0x41, 0xf8, 0xa9, 0x62,
	0x91, 0x2c, 0x1c, 0x01, 0xf1, 0x9f, 0xc5, 0x18, 0x96, 0xde, 0xcf, 0x47, 0xc7, 0x67, 0x18, 0xc7,
	0xa6, 0x42, 0xc3, 0xf5, 0xe9, 0x83, 0x05, 0x2e, 0x11, 0xac, 0x55, 0xce, 0x59, 0xce, 0x7d, 0xed,
	0x79, 0x00, 0x61, 0xd7, 0x11, 0xfc, 0x35, 0x03, 0x26, 0x37, 0x31, 0x36, 0xe8, 0x4f, 0x53, 0xce,
	0xc6, 0x37, 0xd3, 0x14, 0x5d, 0xa5, 0xba, 0x5d, 0xe1, 0xd6, 0x8e, 0xad, 0x0e, 0xa1, 0x5f, 0xbd,
	0xb3, 0xce, 0xa4, 0x43, 0x0b, 0x58, 0x1e, 0x80, 0x5d, 0xbd, 0xa0, 0x68, 0x65, 0x45, 0x3b, 0xb0,
	0xe0, 0x42, 0x57, 0xf2, 0xdf, 0xf4, 0xfe, 0x43, 0x40, 0xdf, 0xba, 0x30, 0x04, 0xef, 0x83, 0xd1,
	0x7b, 0x8a, 0x8a, 0x75, 0x9b, 0xc0, 0x3e, 0x40, 0x7d, 0x91, 0x4f, 0x53, 0xf1, 0x4f, 0xc2, 0xb9,
	0xa0, 0x3d, 0x89, 0x47, 0xac, 0x0a, 0x12, 0x5b, 0xa6, 0xa9, 0x9b, 0x4e, 0xe5, 0xdf, 0xc4, 0x44,
	0x56, 0x6a, 0xd6, 0xc0, 0x0c, 0xce, 0x53, 0x06, 0xaf, 0xc1, 0xc5, 0x90, 0xc3, 0x1c, 0xaa, 0x4f,
	0x14, 0x52, 0x2d, 0x7b, 0x54, 0xbf, 0xc7, 0x00, 0x78, 0x0d, 0x93, 0xe8, 0xd8, 0x77, 0x7c, 0x7b,
	0x11, 0xc1, 0xe8, 0x2b, 0xc6, 0x9b, 0x54, 0x8c, 0xb3, 0xdc, 0x42, 0x50, 0x0c, 0x47, 0x82, 0xa2,
	0x5e, 0xae, 0x0b, 0x0d, 0xa7, 0x99, 0xa0, 0xe3, 0x21, 0xfc, 0x36, 0x03, 0x66, 0xf7, 0x74, 0x8b,
	0x38, 0x14, 0x29, 0x2a, 0x15, 0xe4, 0xc5, 0x26, 0xcc, 0xbe, 0xdc, 0x05, 0xca, 0xfd, 0x02, 0x77,
	0x3e, 0xc8, 0xdd, 0xd0, 0x2d, 0xe2, 0x48, 0x40, 0x7f, 0x6c, 0x74, 0xc5, 0xf0, 0x83, 0x22, 0xf5,
	0x3b, 0xa6, 0x95, 0xff, 0x92, 0x81, 0x95, 0x3e, 0x03, 0x5f, 0xf0, 0x99, 0x19, 0x65, 0x32, 0xe8,
	0x49, 0x55, 0x29, 0x55, 0x91, 0x55, 0xd5, 0xed, 0x5a, 0x99, 0x5e, 0xbf, 0x22, 0x46, 0xb6, 0x85,
	0xcb, 0x48, 0xd1, 0x90, 0x51, 0x93, 0x4b, 0x18, 0xe9, 0x15, 0x7a, 0x51, 0xcb, 0x7a, 0xc9, 0x56,
	0xb1, 0xe6, 0x8e, 0x11, 0xa8, 0xa4, 0xab, 0xce, 0xe2, 0x6c, 0xea, 0x7d, 0xb0, 0xd4, 0xab, 0xa9,
	0x70, 0xae, 0x91, 0x3f, 0x62, 0x0e, 0xfa, 0x4c, 0xf9, 0x18, 0x9c, 0x28, 0xc9, 0x2a, 0xae, 0x6d,
	0xc8, 0x16, 0xf6, 0x68, 0x38, 0xf3, 0x10, 0x94, 0xc0, 0xb0, 0xfb, 0x8b, 0xe9, 0xa0, 0x81, 0xb4,
	0x40, 0x6d, 0x38, 0x07, 0x67, 0x43, 0x81, 0xe4, 0x1c, 0x89, 0x1f, 0x83, 0xc5, 0xbc, 0xa6, 0x93,
	0x2a, 0x36, 0x3d, 0x4e, 0x8e, 0xf3, 0x02, 0x97, 0xea, 0xbd, 0xd0, 0x15, 0x1b, 0x94, 0xf1, 0x50,
	0xe1, 0xcb, 0xd1, 0x56, 0xfe, 0x8b, 0x51, 0xf8, 0x27, 0x06, 0xcc, 0xe5, 0x51, 0xc1, 0x7d, 0x58,
	0x0e, 0xa4, 0x80, 0x0f, 0xc1, 0x89, 0x03, 0x69, 0x6f, 0x23, 0x73, 0xcd, 0x55, 0x1d, 0x19, 0xa6,
	0xfe, 0x18, 0x97, 0xc8, 0xa0, 0x26, 0x4b, 0x25, 0x34, 0x5d, 0xc3, 0xff, 0xe5, 0xa9, 0xe6, 0x40,
	0xa7, 0x3f, 0x06, 0x27, 0x0a, 0x77, 0x37, 0xd1, 0x6a, 0x66, 0xa3, 0x26, 0xdb, 0x16, 0x46, 0xb7,
	0x94, 0x12, 0xd6, 0x2c, 0x0c, 0xb7, 0x07, 0xa3, 0x2c, 0x14, 0x6b, 0x7a, 0x51, 0x50, 0x65, 0x8b,
	0x60, 0x53, 0xb8, 0xb5, 0xb3, 0xb1, 0xb5, 0x7b, 0x77, 0x2b, 0x4b, 0x9e, 0x12, 0x91, 0x5d, 0xc9,
	0x2e, 0xa7, 0x59, 0x26, 0x16, 0x17, 0xbb, 0xca, 0x89, 0x38, 0x1f, 0xdc, 0x79, 0x9a, 0xa9, 0xe8,
	0x7a, 0x46, 0x55, 0x54, 0x9c, 0xeb, 0x82, 0xcc, 0xf5, 0x81, 0x94, 0xf6, 0x9c, 0x8a, 0xb1, 0x0a,
	0x77, 0xc0, 0xb5, 0xee, 0x8a, 0x61, 0x5b, 0xd8, 0xec, 0x54, 0x8b, 0xaa, 0x7c, 0x84, 0x91, 0x81,
	0x4d, 0x55, 0xb1, 0x2c, 0x27, 0x30, 0x89, 0x8e, 0xe4, 0x52, 0x09, 0x5b, 0x56, 0xa8, 0xba, 0x64,
	0xa5, 0x57, 0xa8, 0x41, 0xa3, 0xd2, 0x75, 0xc0, 0xae, 0xad, 0xac, 0xc3, 0x3c, 0x98, 0xda, 0x79,
	0x53, 0x45, 0x32, 0x22, 0x58, 0x36, 0x74, 0x92, 0x85, 0xcb, 0x20, 0x9b, 0x1a, 0xe8, 0xe5, 0xf0,
	0xc1, 0xf7, 0x63, 0x60, 0x06, 0x8c, 0x17, 0x64, 0x4b, 0x29, 0xd1, 0xd1, 0x21, 0x36, 0xc6, 0x80,
	0x33, 0xa1, 0x61, 0x62, 0x66, 0x2c, 0x96, 0x1a, 0xff, 0x30, 0x93, 0xdf, 0xdb, 0xc9, 0xdc, 0xc4,
	0x75, 0x14, 0x03, 0x7f, 0x66, 0xda, 0xc3, 0xc5, 0x1f, 0x98, 0x31, 0x96, 0x8f, 0x8b, 0xe7, 0x7c,
	0x1f, 0x06, 0x1c, 0x2e, 0xe8, 0xb2, 0x4d, 0xaa, 0x82, 0xf3, 0x47, 0x37, 0x95, 0xff, 0xc1, 0xb9,
	0xa5, 0xfe, 0x40, 0x44, 0x3f, 0xc4, 0x5a, 0xe1, 0xff, 0x41, 0xca, 0x9d, 0x55, 0x20, 0xbc, 0x66,
	0xca, 0x1a, 0xb1, 0x90, 0xb3, 0xf0, 0xac, 0x07, 0x16, 0xbd, 0x09, 0x06, 0xce, 0x79, 0x87, 0x74,
	0xe5, 0x9f, 0x6e, 0x80, 0x61, 0xb9, 0xac, 0x2a, 0x1a, 0xcc, 0x85, 0x50, 0xb5, 0x72, 0x08, 0x8c,
	0x3a, 0xc3, 0x01, 0x53, 0x2c, 0xe2, 0x54, 0xa2, 0x23, 0xa7, 0xb3, 0xa8, 0xe8, 0xa6, 0x4a, 0xfd,
	0x5d, 0x5c, 0x02, 0x53, 0x41, 0x53, 0x0c, 0x45, 0xa7, 0xaa, 0xe2, 0x85, 0xbe, 0x73, 0x55, 0x14,
	0xd4, 0xdc, 0x01, 0xa7, 0x6e, 0x77, 0xb2, 0x4f, 0xf0, 0x4e, 0x0d, 0x7a, 0x97, 0x1e, 0x8c, 0xb7,
	0x3d, 0x57, 0x1c, 0xa1, 0xf7, 0x79, 0xf5, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xed, 0x23,
	0x17, 0x1d, 0x28, 0x00, 0x00,
}
